name: Flutter Manual Code Review

on:
  workflow_dispatch:  # Elle başlatmak için

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'  # Projende kullandığın sürümü yazabilirsin

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze > flutter_analyze_report.txt

      - name: Run tests
        run: flutter test --reporter=compact > flutter_test_report.txt

      - name: Show Analyze Report
        run: cat flutter_analyze_report.txt

      - name: Show Test Report
        run: cat flutter_test_report.txt
